gen-classroom/projet-bard_bourcoud_ganguillet_reeve

license.txt

Add a GNU license to the project

---

CODE_OF_CONDUCT

Created code of conduct

---

pom.xml
src/main/java/com/mycompany/app/App.java
src/test/java/com/mycompany/app/AppTest.java

rajout projet maven

---

pom.xml

rajout dependance picocli

---

src/main/java/com/mycompany/app/Main.java
src/main/java/com/mycompany/app/picocli_sub_command/SubCommandClean.java

command clean implémentée (affiche 'clean')

---

.gitignore
src/main/java/com/mycompany/app/Main.java
src/main/java/com/mycompany/app/picocli_sub_command/SubCommandServe.java

Created sub-command serve

---

pom.xml

ajout des dépendances json-simple et commonmark

---

src/main/java/com/mycompany/app/Page.java
src/test/java/com/mycompany/app/PageTest.java

[TOREVIEW] Définir format des pages markdown

---

src/main/java/com/mycompany/app/Main.java
src/main/java/com/mycompany/app/picocli_sub_command/SubCommandInit.java

Pull request + rename subcommand new into init

[TOREVIEW] init subcommand

---

src/main/java/com/mycompany/app/picocli_sub_command/SubCommandClean.java

J'ai implémenté la sous-commande clean, mais sans tests unitaires j'ai fait des tests en dur. De plus il faudrait rajouter une vérif de si la commande est effectué dans le dossier init

[TOREVIEW] Implémentation de la sous-commande clean

---

src/main/java/com/mycompany/app/picocli_sub_command/SubCommandBuild.java
src/test/java/com/mycompany/app/picocli_sub_command_tests/SubCommandBuildTest.java

début de l'implémentation de Build

[TOREVIEW] subCommand Build

---

pom.xml

Ajout de la config du jar dans le pom.xml

[TOREVIEW] Config jar dans pom.xml

---

src/main/java/com/mycompany/app/picocli_sub_command/SubCommandVersion.java

pas trouvé d'autre moyen que d'écrire en dur dans le code
close #22

[TOREVIEW] Nouvelle version de la commande version

---

README.md

Update du README.md. Nous avons ajoutés les instructions d'installations pour la release v0.0.1

Ajout instruction installations

---

src/main/java/com/mycompany/app/picocli_sub_command/SubCommandServe.java
src/main/java/com/mycompany/app/serve/StaticFileHandler.java

[TOREVIEW] Commande serve

---

pom.xml
src/main/java/com/mycompany/app/template/SiteConfig.java

[TOREVIEW] classe siteConfig

---

src/main/java/com/mycompany/app/picocli_sub_command/SubCommandInit.java
src/test/java/com/mycompany/app/picocli_sub_command_tests/SubCommandInitTest.java

Rajout de données dans le config.json
Rajout du dossier template ainsi que les fichier layout.html et menu.html

[TOREVIEW] init sub command upgrade

---

README.md

Mise à jour du README avec ajout notamment de l'utilisation des templates ainsi que des instructions de compilation

[TOREVIEW] Màj du README pour la version 0.0.2 du programme

---

pom.xml

Ajout du plugin javadoc dans le pom.xml afin de pouvoir générer la documentation au format javadoc en exécutant ```mvn javadoc:javadoc```

[TOREVIEW] Javadoc generation

---

src/main/java/com/mycompany/app/picocli_sub_command/SubCommandBuild.java
src/main/java/com/mycompany/app/picocli_sub_command/SubCommandInit.java
src/main/java/com/mycompany/app/picocli_sub_command/SubCommandServe.java
src/test/java/com/mycompany/app/picocli_sub_command_tests/SubCommandBuildTest.java

[TOREVIEW] Génération du site statique à la volée

---

.gitignore
.idea/runConfigurations/AllTests.xml

code coverage avec jacoco sur intellij

[TOREVIEW] Intellij code coverage

---

README.md

Update du README pour l'explication de l'option `--watch`

[TOREVIEW] Add watch instruction
